name: Extrair ZIP na raiz do repositório

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Extrair ZIP na raiz
        run: |
          if [ -f "ZipHeadless_Project.zip" ]; then
            unzip -o ZipHeadless_Project.zip
            echo "ZIP extraído na raiz do repositório!"
          else
            echo "Arquivo ZipHeadless_Project.zip não encontrado."
          fi

      - name: Commitar e enviar alterações
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Atualizar arquivos do projeto a partir do ZIP"
          git push || echo "Nada para commitar"
